export interface Candidate {
  id: number
  name: string
  party: string
  votes: number
  percentage: number
  photo: string
}

export interface Constituency {
  id: number
  seatNumber: number
  name: string
  shortName: string
  leadingParty: string
  winner: Candidate
  candidates: Candidate[]
  totalVoters: number
  turnout: number
  margin: number
}

// Generate mock election data for 20 constituencies in Dhaka
export const constituencies: Constituency[] = [
  {
    id: 1,
    seatNumber: 1,
    name: "Dhaka-1 (Tejgaon)",
    shortName: "Tejgaon",
    leadingParty: "green",
    winner: {
      id: 1,
      name: "Mohammad Rahman",
      party: "green",
      votes: 85420,
      percentage: 48.2,
      photo: "/professional-bangladeshi-man-portrait-1.jpg",
    },
    candidates: [
      {
        id: 1,
        name: "Mohammad Rahman",
        party: "green",
        votes: 85420,
        percentage: 48.2,
        photo: "/professional-bangladeshi-man-portrait-1.jpg",
      },
      {
        id: 2,
        name: "Fatima Begum",
        party: "red",
        votes: 52340,
        percentage: 29.5,
        photo: "/professional-bangladeshi-woman-portrait-1.jpg",
      },
      {
        id: 3,
        name: "Abdul Karim",
        party: "blue",
        votes: 28900,
        percentage: 16.3,
        photo: "/professional-bangladeshi-man-portrait-2.jpg",
      },
      {
        id: 4,
        name: "Rashida Khan",
        party: "independent",
        votes: 10640,
        percentage: 6.0,
        photo: "/professional-bangladeshi-woman-portrait-2.jpg",
      },
    ],
    totalVoters: 245000,
    turnout: 72.3,
    margin: 33080,
  },
  {
    id: 2,
    seatNumber: 2,
    name: "Dhaka-2 (Mirpur)",
    shortName: "Mirpur",
    leadingParty: "red",
    winner: {
      id: 5,
      name: "Salma Akhter",
      party: "red",
      votes: 92150,
      percentage: 51.8,
      photo: "/professional-bangladeshi-woman-portrait-3.jpg",
    },
    candidates: [
      {
        id: 5,
        name: "Salma Akhter",
        party: "red",
        votes: 92150,
        percentage: 51.8,
        photo: "/professional-bangladeshi-woman-portrait-3.jpg",
      },
      {
        id: 6,
        name: "Kamal Hossain",
        party: "green",
        votes: 68420,
        percentage: 38.5,
        photo: "/professional-bangladeshi-man-portrait-3.jpg",
      },
      {
        id: 7,
        name: "Nasir Ahmed",
        party: "independent",
        votes: 17230,
        percentage: 9.7,
        photo: "/professional-bangladeshi-man-portrait-4.jpg",
      },
    ],
    totalVoters: 268000,
    turnout: 66.4,
    margin: 23730,
  },
  {
    id: 3,
    seatNumber: 3,
    name: "Dhaka-3 (Uttara)",
    shortName: "Uttara",
    leadingParty: "green",
    winner: {
      id: 8,
      name: "Aminul Islam",
      party: "green",
      votes: 78900,
      percentage: 45.6,
      photo: "/professional-bangladeshi-man-portrait-5.jpg",
    },
    candidates: [
      {
        id: 8,
        name: "Aminul Islam",
        party: "green",
        votes: 78900,
        percentage: 45.6,
        photo: "/professional-bangladeshi-man-portrait-5.jpg",
      },
      {
        id: 9,
        name: "Rahima Sultana",
        party: "blue",
        votes: 56780,
        percentage: 32.8,
        photo: "/professional-bangladeshi-woman-portrait-4.jpg",
      },
      {
        id: 10,
        name: "Jamal Uddin",
        party: "red",
        votes: 37420,
        percentage: 21.6,
        photo: "/professional-bangladeshi-man-portrait-6.jpg",
      },
    ],
    totalVoters: 232000,
    turnout: 74.6,
    margin: 22120,
  },
  {
    id: 4,
    seatNumber: 4,
    name: "Dhaka-4 (Motijheel)",
    shortName: "Motijheel",
    leadingParty: "blue",
    winner: {
      id: 11,
      name: "Shafiq Ahmed",
      party: "blue",
      votes: 71230,
      percentage: 43.2,
      photo: "/professional-bangladeshi-man-portrait-7.jpg",
    },
    candidates: [
      {
        id: 11,
        name: "Shafiq Ahmed",
        party: "blue",
        votes: 71230,
        percentage: 43.2,
        photo: "/professional-bangladeshi-man-portrait-7.jpg",
      },
      {
        id: 12,
        name: "Nasreen Jahan",
        party: "green",
        votes: 54670,
        percentage: 33.2,
        photo: "/professional-bangladeshi-woman-portrait-5.jpg",
      },
      {
        id: 13,
        name: "Rafiq Hassan",
        party: "red",
        votes: 38900,
        percentage: 23.6,
        photo: "/professional-bangladeshi-man-portrait-8.jpg",
      },
    ],
    totalVoters: 215000,
    turnout: 76.7,
    margin: 16560,
  },
  {
    id: 5,
    seatNumber: 5,
    name: "Dhaka-5 (Gulshan)",
    shortName: "Gulshan",
    leadingParty: "green",
    winner: {
      id: 14,
      name: "Tahmina Alam",
      party: "green",
      votes: 95420,
      percentage: 52.3,
      photo: "/professional-bangladeshi-woman-portrait-6.jpg",
    },
    candidates: [
      {
        id: 14,
        name: "Tahmina Alam",
        party: "green",
        votes: 95420,
        percentage: 52.3,
        photo: "/professional-bangladeshi-woman-portrait-6.jpg",
      },
      {
        id: 15,
        name: "Farhan Ali",
        party: "red",
        votes: 58340,
        percentage: 32.0,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 16,
        name: "Sumon Chowdhury",
        party: "blue",
        votes: 28640,
        percentage: 15.7,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 278000,
    turnout: 65.6,
    margin: 37080,
  },
  {
    id: 6,
    seatNumber: 6,
    name: "Dhaka-6 (Banani)",
    shortName: "Banani",
    leadingParty: "red",
    winner: {
      id: 17,
      name: "Mahmud Hasan",
      party: "red",
      votes: 67890,
      percentage: 44.8,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 17,
        name: "Mahmud Hasan",
        party: "red",
        votes: 67890,
        percentage: 44.8,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 18,
        name: "Shapla Khatun",
        party: "green",
        votes: 52340,
        percentage: 34.5,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 19,
        name: "Imran Khan",
        party: "blue",
        votes: 31370,
        percentage: 20.7,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 198000,
    turnout: 76.5,
    margin: 15550,
  },
  {
    id: 7,
    seatNumber: 7,
    name: "Dhaka-7 (Dhanmondi)",
    shortName: "Dhanmondi",
    leadingParty: "green",
    winner: {
      id: 20,
      name: "Nusrat Jahan",
      party: "green",
      votes: 88760,
      percentage: 49.2,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 20,
        name: "Nusrat Jahan",
        party: "green",
        votes: 88760,
        percentage: 49.2,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 21,
        name: "Rahim Mia",
        party: "red",
        votes: 56890,
        percentage: 31.5,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 22,
        name: "Sakib Rahman",
        party: "independent",
        votes: 34850,
        percentage: 19.3,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 245000,
    turnout: 73.7,
    margin: 31870,
  },
  {
    id: 8,
    seatNumber: 8,
    name: "Dhaka-8 (Mohammadpur)",
    shortName: "M.pur",
    leadingParty: "red",
    winner: {
      id: 23,
      name: "Kabir Hossain",
      party: "red",
      votes: 74560,
      percentage: 46.5,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 23,
        name: "Kabir Hossain",
        party: "red",
        votes: 74560,
        percentage: 46.5,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 24,
        name: "Aisha Siddiqua",
        party: "green",
        votes: 58340,
        percentage: 36.4,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 25,
        name: "Tanvir Ahmed",
        party: "blue",
        votes: 27400,
        percentage: 17.1,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 218000,
    turnout: 73.5,
    margin: 16220,
  },
  {
    id: 9,
    seatNumber: 9,
    name: "Dhaka-9 (Lalbagh)",
    shortName: "Lalbagh",
    leadingParty: "green",
    winner: {
      id: 26,
      name: "Selim Reza",
      party: "green",
      votes: 69870,
      percentage: 47.8,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 26,
        name: "Selim Reza",
        party: "green",
        votes: 69870,
        percentage: 47.8,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 27,
        name: "Monira Begum",
        party: "red",
        votes: 48960,
        percentage: 33.5,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 28,
        name: "Ashraf Uddin",
        party: "blue",
        votes: 27370,
        percentage: 18.7,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 195000,
    turnout: 75.0,
    margin: 20910,
  },
  {
    id: 10,
    seatNumber: 10,
    name: "Dhaka-10 (Hazaribagh)",
    shortName: "H.bagh",
    leadingParty: "blue",
    winner: {
      id: 29,
      name: "Zahir Raihan",
      party: "blue",
      votes: 62450,
      percentage: 44.2,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 29,
        name: "Zahir Raihan",
        party: "blue",
        votes: 62450,
        percentage: 44.2,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 30,
        name: "Rokia Sultana",
        party: "green",
        votes: 48760,
        percentage: 34.5,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 31,
        name: "Masud Rana",
        party: "red",
        votes: 30090,
        percentage: 21.3,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 187000,
    turnout: 75.5,
    margin: 13690,
  },
  {
    id: 11,
    seatNumber: 11,
    name: "Dhaka-11 (Kamrangirchar)",
    shortName: "K.char",
    leadingParty: "red",
    winner: {
      id: 32,
      name: "Nazma Akter",
      party: "red",
      votes: 58970,
      percentage: 43.6,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 32,
        name: "Nazma Akter",
        party: "red",
        votes: 58970,
        percentage: 43.6,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 33,
        name: "Habib Rahman",
        party: "green",
        votes: 47650,
        percentage: 35.2,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 34,
        name: "Shahin Mia",
        party: "independent",
        votes: 28680,
        percentage: 21.2,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 178000,
    turnout: 76.0,
    margin: 11320,
  },
  {
    id: 12,
    seatNumber: 12,
    name: "Dhaka-12 (Kotwali)",
    shortName: "Kotwali",
    leadingParty: "green",
    winner: {
      id: 35,
      name: "Jahanara Imam",
      party: "green",
      votes: 72340,
      percentage: 48.5,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 35,
        name: "Jahanara Imam",
        party: "green",
        votes: 72340,
        percentage: 48.5,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 36,
        name: "Badrul Alam",
        party: "red",
        votes: 52890,
        percentage: 35.5,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 37,
        name: "Salim Uddin",
        party: "blue",
        votes: 23870,
        percentage: 16.0,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 203000,
    turnout: 73.5,
    margin: 19450,
  },
  {
    id: 13,
    seatNumber: 13,
    name: "Dhaka-13 (Sutrapur)",
    shortName: "Sutrapur",
    leadingParty: "blue",
    winner: {
      id: 38,
      name: "Anwar Hossain",
      party: "blue",
      votes: 65780,
      percentage: 45.3,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 38,
        name: "Anwar Hossain",
        party: "blue",
        votes: 65780,
        percentage: 45.3,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 39,
        name: "Kulsum Begum",
        party: "green",
        votes: 48920,
        percentage: 33.7,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 40,
        name: "Faisal Khan",
        party: "red",
        votes: 30500,
        percentage: 21.0,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 192000,
    turnout: 75.7,
    margin: 16860,
  },
  {
    id: 14,
    seatNumber: 14,
    name: "Dhaka-14 (Sabujbagh)",
    shortName: "S.bagh",
    leadingParty: "red",
    winner: {
      id: 41,
      name: "Hasina Khatun",
      party: "red",
      votes: 71450,
      percentage: 46.8,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 41,
        name: "Hasina Khatun",
        party: "red",
        votes: 71450,
        percentage: 46.8,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 42,
        name: "Rubel Ahmed",
        party: "green",
        votes: 54670,
        percentage: 35.8,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 43,
        name: "Kawsar Ali",
        party: "blue",
        votes: 26580,
        percentage: 17.4,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 208000,
    turnout: 73.5,
    margin: 16780,
  },
  {
    id: 15,
    seatNumber: 15,
    name: "Dhaka-15 (Ramna)",
    shortName: "Ramna",
    leadingParty: "green",
    winner: {
      id: 44,
      name: "Shamsul Haque",
      party: "green",
      votes: 82340,
      percentage: 50.2,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 44,
        name: "Shamsul Haque",
        party: "green",
        votes: 82340,
        percentage: 50.2,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 45,
        name: "Ruma Akter",
        party: "red",
        votes: 56780,
        percentage: 34.6,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 46,
        name: "Motin Sarker",
        party: "independent",
        votes: 24880,
        percentage: 15.2,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 225000,
    turnout: 72.9,
    margin: 25560,
  },
  {
    id: 16,
    seatNumber: 16,
    name: "Dhaka-16 (Pallabi)",
    shortName: "Pallabi",
    leadingParty: "independent",
    winner: {
      id: 47,
      name: "Iqbal Hussain",
      party: "independent",
      votes: 58670,
      percentage: 42.5,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 47,
        name: "Iqbal Hussain",
        party: "independent",
        votes: 58670,
        percentage: 42.5,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 48,
        name: "Sharmin Jahan",
        party: "green",
        votes: 45890,
        percentage: 33.2,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 49,
        name: "Zahid Hasan",
        party: "red",
        votes: 33540,
        percentage: 24.3,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 185000,
    turnout: 74.6,
    margin: 12780,
  },
  {
    id: 17,
    seatNumber: 17,
    name: "Dhaka-17 (Turag)",
    shortName: "Turag",
    leadingParty: "blue",
    winner: {
      id: 50,
      name: "Mamun Rashid",
      party: "blue",
      votes: 69450,
      percentage: 47.2,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 50,
        name: "Mamun Rashid",
        party: "blue",
        votes: 69450,
        percentage: 47.2,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 51,
        name: "Bilkis Banu",
        party: "green",
        votes: 52340,
        percentage: 35.6,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 52,
        name: "Arif Mahmud",
        party: "red",
        votes: 25310,
        percentage: 17.2,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 198000,
    turnout: 74.4,
    margin: 17110,
  },
  {
    id: 18,
    seatNumber: 18,
    name: "Dhaka-18 (Khilkhet)",
    shortName: "Khilkhet",
    leadingParty: "green",
    winner: {
      id: 53,
      name: "Farida Yasmin",
      party: "green",
      votes: 76890,
      percentage: 49.5,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 53,
        name: "Farida Yasmin",
        party: "green",
        votes: 76890,
        percentage: 49.5,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 54,
        name: "Shakil Ahmed",
        party: "red",
        votes: 48670,
        percentage: 31.3,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 55,
        name: "Rony Mia",
        party: "blue",
        votes: 29840,
        percentage: 19.2,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 212000,
    turnout: 73.3,
    margin: 28220,
  },
  {
    id: 19,
    seatNumber: 19,
    name: "Dhaka-19 (Vatara)",
    shortName: "Vatara",
    leadingParty: "red",
    winner: {
      id: 56,
      name: "Mostafa Kamal",
      party: "red",
      votes: 68940,
      percentage: 45.8,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 56,
        name: "Mostafa Kamal",
        party: "red",
        votes: 68940,
        percentage: 45.8,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 57,
        name: "Lipi Rahman",
        party: "green",
        votes: 54230,
        percentage: 36.0,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 58,
        name: "Rubel Khan",
        party: "independent",
        votes: 27330,
        percentage: 18.2,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 205000,
    turnout: 73.4,
    margin: 14710,
  },
  {
    id: 20,
    seatNumber: 20,
    name: "Dhaka-20 (Dakshinkhan)",
    shortName: "D.khan",
    leadingParty: "independent",
    winner: {
      id: 59,
      name: "Liton Mia",
      party: "independent",
      votes: 55670,
      percentage: 41.2,
      photo: "/placeholder.svg?height=80&width=80",
    },
    candidates: [
      {
        id: 59,
        name: "Liton Mia",
        party: "independent",
        votes: 55670,
        percentage: 41.2,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 60,
        name: "Sahana Akter",
        party: "green",
        votes: 48920,
        percentage: 36.2,
        photo: "/placeholder.svg?height=60&width=60",
      },
      {
        id: 61,
        name: "Babul Hossain",
        party: "red",
        votes: 30510,
        percentage: 22.6,
        photo: "/placeholder.svg?height=60&width=60",
      },
    ],
    totalVoters: 178000,
    turnout: 75.9,
    margin: 6750,
  },
]
